### ISSUE TITLE
exception  Permission denied

### ISSUE THREAD

**Issue by rafiw** [gak/pycallgraph#100]
Caught exception, will raise after graph is made.
Creating pycallgraph.png
pycallgraph.png: Permission denied
Traceback (most recent call last):
  File "/usr/local/bin/pycallgraph", line 5, in <module>
    pkg_resources.run_script('pycallgraph==0.5.1', 'pycallgraph')
  File "/usr/local/lib64/python2.6/site-packages/distribute-0.6.30-py2.6.egg/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib64/python2.6/site-packages/distribute-0.6.30-py2.6.egg/pkg_resources.py", line 1239, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib64/python2.6/site-packages/pycallgraph-0.5.1-py2.6.egg/EGG-INFO/scripts/pycallgraph", line 161, in <module>
    pycallgraph.make_dot_graph(options.output_file, options.format, options.tool)
  File "/usr/local/lib64/python2.6/site-packages/pycallgraph-0.5.1-py2.6.egg/pycallgraph.py", line 386, in make_dot_graph
    'code %(ret)i.' % locals())
pycallgraph.PyCallGraphException: The command "dot -Tpng -opycallgraph.png /tmp/tmpnrM5wl" failed with error code 256.

**Comment by adrientetar** [comment]
I get the same issue and I do have permission to write in the current directory.

~~~
	%0 1
	%0 1
	%0 1
	%0 2
dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.442253 to fit
Traceback (most recent call last):
  File "ufoLib_test.py", line 12, in <module>
    profile()
  File "/home/adrien/.local/lib/python3.6/site-packages/pycallgraph/pycallgraph.py", line 38, in __exit__
    self.done()
  File "/home/adrien/.local/lib/python3.6/site-packages/pycallgraph/pycallgraph.py", line 81, in done
    self.stop()
  File "/home/adrien/.local/lib/python3.6/site-packages/pycallgraph/pycallgraph.py", line 90, in generate
    output.done()
  File "/home/adrien/.local/lib/python3.6/site-packages/pycallgraph/output/graphviz.py", line 112, in done
    'code %(ret)i.' % locals())
pycallgraph.exceptions.PyCallGraphException: The command "dot -Tpng -opycallgraph.png /tmp/tmpb75rmcmi" failed with error code 256.
~~~

I installed pycallgraph from pip3 and graphviz from ubuntu apt.
