### ISSUE TITLE
pycallgraph executable not created on install

### ISSUE THREAD

**Issue by roger-butler** [gak/pycallgraph#119]
I downloaded pycallgraph 1.0.1 and untarred it into a temporary directory. My Python environment is Enthought Canopy 1.1 on Windows 7. I ran easy_install pip to install pip, then pip install pycallgraph. Files were copied to my Python environment but not an executable. So I can run pycallgraph using the API but not the command line.

Any ideas?

**Comment by joris255** [comment]
Thank you Kuba !

**Comment by Tibbar49** [comment]
Jakub's solution seems more elegant than mine. I would try his instead.

**Comment by suurjaak** [comment]
There is a better solution: pip supports [automatic script creation](https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation). If setup.py used `entry_points` instead of `scripts`, it would create .exe files in Windows.

There would need to be a single entry method in pycallgraph, and this in setup.py:

    entry_points={"console_scripts": ["pycallgraph = pycallgraph.pycallgraph:yourentrymethod"]},

**Comment by Andrej730** [comment]
C:\Users\Andrey>pycallgraph
Traceback (most recent call last):
  File "C:\Python34\Scripts\pycallgraph", line 19, in <module>
    __config.strip_argv()
  File "C:\Python34\lib\site-packages\pycallgraph\config.py", line 69, in strip_
argv
    sys.argv = [self.command] + self.command_args
AttributeError: 'Config' object has no attribute 'command'

getting this error when calling pycallgraph with jakubczaplicki

**Comment by avishapiro** [comment]
Thanks @jakubczaplicki . That worked for me. I'm using Python 3.5 from the Anaconda distribution so I put the new pycallgraph.bat file in a different path (`C:\Anaconda3\Scripts\`), where pycallgraph (no extension) is located, exactly as you instructed.
