### ISSUE TITLE
pip install fails in python3

### ISSUE THREAD

**Issue by earthspike** [gak/pycallgraph#141]
It looks like pycallgraph/output/gephi.py is using python 2.x style syntax:
```
Downloading/unpacking pycallgraph (from -r requirements/dev.txt (line 9))
  Downloading pycallgraph-1.0.1.tar.gz
  Running setup.py egg_info for package pycallgraph
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/projects/acme_project/virtualenv/acme/build/pycallgraph/setup.py", line 9, in <module>
        import pycallgraph
      File "pycallgraph/__init__.py", line 15, in <module>
        from .pycallgraph import PyCallGraph
      File "pycallgraph/pycallgraph.py", line 3, in <module>
        from .output import Output
      File "pycallgraph/output/__init__.py", line 5, in <module>
        from .gephi import GephiOutput
      File "pycallgraph/output/gephi.py", line 28
        return u'\n'.join([
                   ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/projects/acme_project/virtualenv/acme/build/pycallgraph/setup.py", line 9, in <module>

    import pycallgraph

  File "pycallgraph/__init__.py", line 15, in <module>

    from .pycallgraph import PyCallGraph

  File "pycallgraph/pycallgraph.py", line 3, in <module>

    from .output import Output

  File "pycallgraph/output/__init__.py", line 5, in <module>

    from .gephi import GephiOutput

  File "pycallgraph/output/gephi.py", line 28

    return u'\n'.join([

               ^

SyntaxError: invalid syntax
```

**Comment by hayd** [comment]
Are you using python >= 3.3 ?

**Comment by earthspike** [comment]
I don't think I was as it was on an Ubuntu 12.04 machine with Python 3.2.3. I switched to Python 3.4.3 and all now seems fine.

**Comment by msjaiswal** [comment]
Is pycallgraph supposed to work on python 3.4 ?

**Comment by hayd** [comment]
According to the README (and also the travis.yml)

> Support for Python 2.7+ and Python 3.3+.

**Comment by gak** [comment]
Closing as @earthspike was using Python 3.2 which is not supported.
