### ISSUE TITLE
Graphviz fails to build output

### ISSUE THREAD

**Issue by Dreen** [gak/pycallgraph#150]
When generating output for my profiled code I get the following error:

```
libpath/shortest.c:324: triangulation failed
libpath/shortest.c:192: source point not in any triangle
Error: in routesplines, Pshortestpath failed
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/usr/local/bin/pycallgraph", line 26, in <module>
    exec(__file_content)
  File "/usr/local/lib/python3.4/dist-packages/pycallgraph/pycallgraph.py", line 38, in __exit__
    self.done()
  File "/usr/local/lib/python3.4/dist-packages/pycallgraph/pycallgraph.py", line 81, in done
    self.stop()
  File "/usr/local/lib/python3.4/dist-packages/pycallgraph/pycallgraph.py", line 90, in generate
    output.done()
  File "/usr/local/lib/python3.4/dist-packages/pycallgraph/output/graphviz.py", line 112, in done
    'code %(ret)i.' % locals())
pycallgraph.exceptions.PyCallGraphException: The command "dot -Tpng -opycallgraph.png /tmp/tmpjxrt96s0" failed with error code 35584.
```

**Comment by gak** [comment]
`Segmentation fault (core dumped)`

This might be a graphviz error. I can see a few bug report on theirs issue tracker:
http://www.graphviz.org/mantisbt/view.php?id=2382
http://www.graphviz.org/mantisbt/view.php?id=2246

The latter might have a solution about changing the splines setting.

Can you show a reproducible example, and give me the environment specs?

**Comment by evgeniikozhanov** [comment]
I decrease max_depth, and it's work for me.

**Comment by ghost** [comment]
Hello, i found a workaround and what you can do is when you call dot pass as an argument: -Gnewrank=true without specifying max_depth and it will work!

**Comment by yuvalneteera** [comment]
> I decrease max_depth, and it's work for me.

worked for me too thanks!
