### ISSUE TITLE
failed to build graph with error code 34304

### ISSUE THREAD

**Issue by delbao** [gak/pycallgraph#159]
Aborted
Traceback (most recent call last):
  File "/nail/home/dbao/github/helenus/myenv2.7/bin/pycallgraph", line 26, in <module>
    exec(__file_content)
  File "/nail/home/dbao/github/helenus/myenv2.7/local/lib/python2.7/site-packages/pycallgraph/pycallgraph.py", line 38, in __exit__
    self.done()
  File "/nail/home/dbao/github/helenus/myenv2.7/local/lib/python2.7/site-packages/pycallgraph/pycallgraph.py", line 81, in done
    self.stop()
  File "/nail/home/dbao/github/helenus/myenv2.7/local/lib/python2.7/site-packages/pycallgraph/pycallgraph.py", line 90, in generate
    output.done()
  File "/nail/home/dbao/github/helenus/myenv2.7/local/lib/python2.7/site-packages/pycallgraph/output/graphviz.py", line 112, in done
    'code %(ret)i.' % locals())
pycallgraph.exceptions.PyCallGraphException: The command "dot -Tpng -opycallgraph.png /nail/tmp/tmpL5N2N1" failed with error code 34304.

I also tried manually run 'dot' with -v. it aborted with
....
        virtual 1
network simplex: 100 200 300 400 500 600 700 800 900 1000
network simplex: 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000
network simplex: 2100 2200 2300 2400 2500 2600 2700 2800 2900 3000
network simplex: 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000
network simplex: 4100 4200 4300 4400 4500 4600 4700 4800 4900 5000
network simplex: 5100 5200 5300 5400 5500 5600 5700 5800 5900 6000
network simplex: 6100 6200 6300 6400 6500 6600 6700 6800 6900
network simplex: 11178 nodes 19379 edges 6920 iter 6.39 sec
in checkpath, boxes 0 and 1 don't touch
2 boxes:
0 (-39435, 500), (-39188, 568)
1 (-40239, 500), (-40094, 568)
start port: (-39313, 500), tangent angle: 0.000, not constrained
end port: (-40169, 500), tangent angle: 0.000, not constrained
Aborted

**Comment by regisz** [comment]
me too :(
